### ISSUE TITLE
Minor: Gold scaling cards in post combat don't account for gold acquired that fight

### ISSUE THREAD

**Issue by SilentJ28** [JohnnyBazooka89/StSModTheBlackbeard#1]
Example: Golden strike says 163 gold this run. Have actually gained 195 after this fight and when I look at the upgrade for the card it shows me that correct value.

Would also be nice if these cards did the math for me on 1% of my gold (despite how easy that math is)

**Comment by JohnnyBazooka89** [comment]
Thank you for pointing it out.

**Comment by JohnnyBazooka89** [comment]
It should be fixed in the next released version.
