### ISSUE TITLE
Cannon Barrage Tweak

### ISSUE THREAD

**Issue by Bartholomue** [JohnnyBazooka89/StSModTheBlackbeard#13]
As it stands, Cannon Barrage doesn't do anything special -- it just gives you a bunch of strikes -- 6 damage per every 1 energy. Would it be unbalanced to change it to give X + 1 by default, with the upgrade giving Cannonball+'s? I know it can scale with Final Barrage, but that's assuming you even get that card.

**Comment by JohnnyBazooka89** [comment]
I guess you are right, Cannon Barrage seems a little bit weak. I buffed it in v.2.5.0

**Comment by JohnnyBazooka89** [comment]
Also funny story: I noticed later that after the buff, the card "Cannonball Supply" becomes strictly worse than the new Cannon Barrage. I had to buff that one too.
