### ISSUE TITLE
Rearming Strike Rework

### ISSUE THREAD

**Issue by Bartholomue** [JohnnyBazooka89/StSModTheBlackbeard#14]
I always want to love rearming strike, but I quite often skip over it, because it's not really doing anything different from having a cutlass (especially when upgraded). Would you consider changing Rearm so that it does damage, then draws a random weapon card out of your draw pile? When upgraded, it would let you pick which weapon card to draw. This would give the card some functional purpose as a card manipulator.

**Comment by JohnnyBazooka89** [comment]
I quite agree that this card is not anything special at the moment, it was designed mostly as an early game elite solution, strong common attack that is especially good against Gremlin Nob.

I think your idea is pretty cool, but unfortunately it requires quite a lot of effort to implement it. I will keep this card as is.

**Comment by Bartholomue** [comment]
Awesome. Thanks for entertaining my ideas. :)
