### ISSUE TITLE
Sword Dance doesn't use durability for the extra weapons?

### ISSUE THREAD

**Issue by SilentJ28** [JohnnyBazooka89/StSModTheBlackbeard#2]
I used sword dance expecting to be able to set off the powder keg in my 3rd weapon slot but it seems the powder keg was not reduced in durability?

The way it currently works is a huge buff to sword dance outside of powder keg but wasn't what I expected

**Comment by JohnnyBazooka89** [comment]
I just checked the interaction and I think it works as expected.

![javaw_2018-10-15_19-13-08](https://user-images.githubusercontent.com/43926043/46966588-74f68500-d0ae-11e8-976a-86790d16be9e.jpg)

The setup is Cutlass, upgraded Powder Keg and Sword Dance. Then i use the strike.

![javaw_2018-10-15_19-13-38](https://user-images.githubusercontent.com/43926043/46966589-7627b200-d0ae-11e8-8243-1e6093805d6a.jpg)

Jaw Worm was dealt 29 card (6 for strike, 3 for cutlass and 20 for upgraded Powder Keg).

Maybe there were some other interactions happening? Also are you sure are you using version 0.0.5?

**Comment by JohnnyBazooka89** [comment]
I fixed the interaction with cards created automatically (like Necronomicon, Parrot or cards from other classes like Echo Form, Double Tap etc). It should work property now.
