### ISSUE TITLE
Rum gives test1 ability

### ISSUE THREAD

**Issue by bug-sniper** [JohnnyBazooka89/StSModTheBlackbeard#6]
Rum's description says it should give you 2 resistance. I have the hip flash relic (which gives 1 to resistance) and it gives me the test1 ability instead, which does nothing appearantly.

**Comment by JohnnyBazooka89** [comment]
Oh, yes, sorry for that :/

I uploaded wrong jar to Steam Workshop, I hotfixed this already. It should be fine now. If the problem persists, please reopen this issue.
